name: SSH-Compose
description: SSH into host and deploy repository with Docker-Compose
inputs:
  ssh_private_key:
    description: Private SSH key used for logging into remote system.
    required: true
  ssh_host:
    description: Remote host name.
    required: true
  ssh_port:
    description: Remote SSH port.
    default: 22
    required: true
  ssh_user:
    description: Remote user name.
    required: true
  docker_compose_prefix:
    description: Prefix for docker-compose containers.
    required: true
  docker_compose_filename:
    description: Docker compose file to use
    default: docker-compose.yaml
  use_stack:
    description: Use docker stack instead of docker compose ("true" or "false").
    default: 'false'
  tar_package_operation_modifiers:
    description: Tar operation modifiers used while creating the package.
    default: '--exclude .git --exclude .github --exclude .gitignore --exclude .gitmodules --exclude .vscode'
runs:
  using: docker
  image: Dockerfile
  env:
    SSH_USER: ${{ inputs.ssh_user }}
    SSH_HOST: ${{ inputs.ssh_host }}
    SSH_PORT: ${{ inputs.ssh_port }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    DOCKER_COMPOSE_FILENAME: ${{ inputs.docker_compose_filename }}
    DOCKER_COMPOSE_PREFIX: ${{ inputs.docker_compose_prefix }}
    USE_DOCKER_STACK: ${{ inputs.use_stack }}
    TAR_PACKAGE_OPERATION_MODIFIERS: ${{ inputs.tar_package_operation_modifiers }}
